### ISSUE TITLE
Override template & css

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [wefork/wekan#89] opened 2017-01-26 09:31 UTC
Hi,

I'm quite new on meteor, and i'm challenging my self in customizing this awesome app for my needs.

**Css**
I see a lot of stylus files, but i don't how to override some styles without breaking code projets (in case of some future code fixes).

I don't find any global style files which import all styles.
Is stylus making some magics to build/merge/include a single css file ?

 **Template**
In blaze, is there any way to override a template ? 

thanks,
Nelson

**Comment by xet7** [comment] 2017-01-26 14:04
@tugal 

In meteor build process templates, CSS, javascript etc is combined and minimized.
https://github.com/wefork/wekan/wiki/Install-from-source
and in there:
meteor build .build --directory

Those Install from source instructions may need fixes as some did not get it working. VirtualBox appliance at https://wekan.xet7.org does work.

At Wefork there is only little documentation, you could look is it of any help:
https://github.com/wefork/wekan/wiki/Developer-Documentation

Otherwise you mostly need to refer to Meteor and Blaze documentation.

**Comment by xet7** [comment] 2017-02-06 06:56
Duplicate of https://github.com/wekan/wekan/issues/781 , continue discussion there.

**Closed as completed by xet7** 2017-02-06 06:56 UTC
