### ISSUE TITLE
Add feature: Email to board / email to card / script to card

### ISSUE THREAD

**Issue by quimnuss** [wefork/wekan#48] opened 2016-12-15 11:33 UTC
It be nice to be able to post to card by writting an e-mail.

Alternatively, how could a script on the server add a card/comment ?

I'm testing different options before commiting to one project :)

I'd try to implement it myself if necessary, but I just found wekan a couple days ago :)

Superseedes #42

**Comment by quimnuss** [comment] 2016-12-15 11:34
Reference to the same feature request:

https://github.com/wekan/wekan/issues/339

**Comment by xet7** [comment] 2016-12-15 11:38
@quimnuss 

This issue is duplicate of #42 , please continue discussion there.

**Comment by quimnuss** [comment] 2016-12-15 11:39
I just saw it, I think this one superseedes the #42, don't you think?

**Closed as completed by xet7** 2016-12-15 11:38 UTC

**Comment by xet7** [comment] 2016-12-15 11:50
@quimnuss 

I can change title of #42 when the idea is more developed. Please add the relevant info and wekan issue links as one comment to #42 because this issue is becoming more messy with constant closing and opening of issue.

**Comment by quimnuss** [comment] 2016-12-15 12:05
Agreed
